version: '3.8'
services:
  kirana-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.docker
    depends_on:
      - mysql
    volumes:
      - uploads:/app/uploads
    networks:
      - kirana-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: kirana_pos
      MYSQL_USER: kirana_user
      MYSQL_PASSWORD: Mandla@12_strong_prod_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kirana-net

volumes:
  mysql_data:
  uploads:

networks:
  kirana-net:
    driver: bridge
