import { openDB } from "./db";
import { getCustomerLoyalty } from "./loyaltyEngine";
import { createCoupon } from "./couponService";


export async function evaluateAutoCoupon(customerName, amount){

  const db = await openDB();

  const tx =
    db.transaction("customer_profiles","readonly");

  const store =
    tx.objectStore("customer_profiles");

  const profile =
    await store.get(customerName);

  if(!profile) return;


  /* RULE 1 — SPEND MILESTONE */

  const milestones = [5000,15000,50000];

  for(const milestone of milestones){

    if(
      profile.lifetimeSpend >= milestone &&
      !profile[`reward_${milestone}`]
    ){

      await generateRewardCoupon(
        customerName,
        milestone
      );

      profile[`reward_${milestone}`] = true;

      const tx2 =
        db.transaction("customer_profiles","readwrite");

      tx2.objectStore("customer_profiles")
        .put(profile);

    }

  }

}


async function generateRewardCoupon(customerName, milestone){

  const discount =
    Math.floor(milestone * 0.02); // 2%

  const coupon = {

    id: crypto.randomUUID(),

    title:
      "Loyalty Reward",

    code:
      "REWARD-" +
      milestone +
      "-" +
      Date.now(),

    value: discount,

    minPurchase:
      discount * 5,

    loyaltyRequired:
      await getCustomerLoyalty(customerName),

    expiryDate:
      getExpiryDate(7),

    active: true,

    autoGenerated: true,

    createdAt: Date.now()

  };

  await createCoupon(coupon);

}


function getExpiryDate(days){

  const d = new Date();

  d.setDate(d.getDate()+days);

  return d.toISOString();

}