import { openDB, getShopSettings } from "./db";
import { createCoupon } from "./couponService";

export async function evaluateAutoCoupon(customerId, amount){

  if (!customerId || amount <= 0) return;

  const db = await openDB();

  const milestonesToReward = [];

  return new Promise((resolve, reject) => {

    const tx = db.transaction("customers","readwrite");
    const store = tx.objectStore("customers");

    const getReq = store.get(customerId);

    getReq.onsuccess = () => {

      const customer = getReq.result;
      if(!customer){
        resolve();
        return;
      }

      const milestones = [5000,15000,50000];

      for(const milestone of milestones){

        if(
          (customer.lifetimeSpend || 0) >= milestone &&
          !customer[`reward_${milestone}`]
        ){
          customer[`reward_${milestone}`] = true;
          milestonesToReward.push(milestone);
        }
      }

      store.put(customer);
    };

    tx.oncomplete = async () => {

      // Generate coupons AFTER transaction safely completes
      for(const milestone of milestonesToReward){
        await generateRewardCoupon(customerId, milestone);
      }

      resolve();
    };

    tx.onerror = () => reject(tx.error);
  });
}

async function generateRewardCoupon(customerId, milestone){

  const shopSettings = await getShopSettings();
  const shopId = shopSettings?.shopId;

  // Reward formula (safe for retail margins)
  let discount;
  let minPurchase;

  if(milestone === 5000){
    discount = 50;
    minPurchase = 300;
  }

  else if(milestone === 15000){
    discount = 120;
    minPurchase = 700;
  }

  else if(milestone === 50000){
    discount = 400;
    minPurchase = 2000;
  }

  const coupon = {
    id: crypto.randomUUID(),
    customerId,
    shopId,

    title: "Loyalty Reward",

    code:
      "REWARD-" +
      milestone +
      "-" +
      Date.now(),

    value: discount,
    minPurchase,

    expiryDate: getExpiryDate(10),

    active: true,
    autoGenerated: true,
    createdAt: Date.now()
  };

  await createCoupon(coupon);
}