import { openDB } from "./db";
import { createCoupon } from "./couponService";

export async function evaluateAutoCoupon(customerId, amount){

  if (!customerId || amount <= 0) return;

  const db = await openDB();

  const milestonesToReward = [];

  return new Promise((resolve, reject) => {

    const tx = db.transaction("customers","readwrite");
    const store = tx.objectStore("customers");

    const getReq = store.get(customerId);

    getReq.onsuccess = () => {

      const customer = getReq.result;
      if(!customer){
        resolve();
        return;
      }

      const milestones = [5000,15000,50000];

      for(const milestone of milestones){

        if(
          (customer.lifetimeSpend || 0) >= milestone &&
          !customer[`reward_${milestone}`]
        ){
          customer[`reward_${milestone}`] = true;
          milestonesToReward.push(milestone);
        }
      }

      store.put(customer);
    };

    tx.oncomplete = async () => {

      // Generate coupons AFTER transaction safely completes
      for(const milestone of milestonesToReward){
        await generateRewardCoupon(customerId, milestone);
      }

      resolve();
    };

    tx.onerror = () => reject(tx.error);
  });
}

async function generateRewardCoupon(customerId, milestone){

  const discount = Math.floor(milestone * 0.02);

  const coupon = {
    id: crypto.randomUUID(),
    customerId,
    title: "Loyalty Reward",
    code: "REWARD-" + milestone + "-" + Date.now(),
    value: discount,
    minPurchase: discount * 5,
    expiryDate: getExpiryDate(7),
    active: true,
    autoGenerated: true,
    createdAt: Date.now()
  };

  await createCoupon(coupon);
}

function getExpiryDate(days){
  const d = new Date();
  d.setDate(d.getDate()+days);
  return d.toISOString();
}